services:
  ubuntu-nuxeo:
    build: .
    container_name: nuxeo-ubuntu
    env_file: .env
    stdin_open: true
    tty: true
    ports:
      - 8082:8080
    networks:
      - nuxeo
    volumes:
      - ./src/client:/opt/client
      - ./src/server:/opt/server
    environment:
      NUXEO_DEV: ${NX_DEV}
      NUXEO_CLID: ${NX_CLID}
      NUXEO_PACKAGES: ${NX_PACKAGES}
      NUXEO_INSTALL_HOTFIX: ${NX_INSTALL_HOTFIX}
      NUXEO_DB_TYPE: ${NX_DB_TYPE}
      NUXEO_DB_NAME: ${NX_DB_NAME}
      NUXEO_DB_USER: ${NX_DB_USER}
      NUXEO_DB_PASSWORD: ${NX_DB_PASSWORD}
      NUXEO_DB_HOST: ${NX_DB_HOST}
      NUXEO_DB_PORT: ${NX_DB_PORT}
networks:
  nuxeo:
    driver: bridge
    name: ubuntu-nuxeo
